Media.Web/Models/AccountModels.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Globalization;
using System.Web.Security;

namespace Media.Web.Models
{
    public class UsersContext : DbContext
    {
        public UsersContext()
            : base("DefaultConnection")
        {
        }

        public DbSet<UserProfile> UserProfiles { get; set; }
    }

    [Table("UserProfile")]
    public class UserProfile
    {
        [Key]
        [DatabaseGeneratedAttribute(DatabaseGeneratedOption.Identity)]
        public int UserId { get; set; }
        public string UserName { get; set; }
    }

    public class RegisterExternalLoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        public string ExternalLoginData { get; set; }
    }

    public class LocalPasswordModel
    {
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Current password")]
        public string OldPassword { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "New password")]
        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm new password")]
        [Compare("NewPassword", ErrorMessage = "The new password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class LoginModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [Display(Name = "Remember me?")]
        public bool RememberMe { get; set; }
    }

    public class RegisterModel
    {
        [Required]
        [Display(Name = "User name")]
        public string UserName { get; set; }

        [Required]
        [StringLength(100, ErrorMessage = "The {0} must be at least {2} characters long.", MinimumLength = 6)]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm password")]
        [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
        public string ConfirmPassword { get; set; }
    }

    public class ExternalLogin
    {
        public string Provider { get; set; }
        public string ProviderDisplayName { get; set; }
        public string ProviderUserId { get; set; }
    }
}

Media.Web/Controllers/TitlesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Media.Web.Models;
using Movie.Web.MediaServiceReference;


namespace Media.Web.Controllers
{
    public class TitlesController : Controller
    {
        // Invoking Media Service Instances.
        public MediaServiceClient mediaService = new MediaServiceClient();
        // Loading all the Titles.
        public ActionResult Index()
        {
            return View(mediaService.Default());
        }
        //Filtering Title List by Title
        [HttpPost]
        public ActionResult Index(string TitleSearch)
        {
            var Title = mediaService.GetMediaList(TitleSearch).ToList();

            return View(Title);
        }
        // Getting Title Details for single Title
        public ActionResult Details(int id = 0)
        {
            string GenreName = "";

            var Title = mediaService.GetMediaDetails(id);
            if (Title == null)
            {
                return HttpNotFound();
            }
            else
            {
                foreach (var n in mediaService.GetGenreList(id).ToList())
                {
                    GenreName = GenreName + n.Name + " | ";
                }

                ViewBag.GenreName = GenreName.Remove(GenreName.LastIndexOf("|"));

            }
            return View(Title);
        }
        //// Getting Award Details for Title
        public ActionResult AwardDetails(int TitleId = 0)
        {
            var Award = mediaService.GetAwardList(TitleId).ToList();
            if (Award == null)
            {
                return HttpNotFound();
            }
            else
            {
                ViewBag.TitleName = mediaService.GetMediaDetails(TitleId).TitleName;
            }

            return View(Award);
        }
        //// Getting Cast Details for Title
        public ActionResult Cast(int TitleId = 0)
        {
            var Cast = mediaService.GetCastList(TitleId).ToList();
            if (Cast == null)
            {
                return HttpNotFound();
            }
            else
            {
                ViewBag.TitleName = mediaService.GetMediaDetails(TitleId).TitleName;
            }
            return View(Cast);
        }
        // //Getting StoryLines Details for Title
        public ActionResult StoryLines(int TitleId = 0)
        {

            var StoryLines = mediaService.GetStoryLineList(TitleId).ToList();
            if (StoryLines == null)
            {
                return HttpNotFound();
            }
            else
            {
                ViewBag.TitleName = mediaService.GetMediaDetails(TitleId).TitleName;
                return View(StoryLines);
            }

        }
    }
}

Media.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">                
                <div class="float-right">                   
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index")</li>                            
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>        

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

Media.Web/Views/Titles/AwardDetails.cshtml
@model IEnumerable<Movie.Web.MediaServiceReference.Award>
<html>
<link href="~/Content/Title.css" rel="stylesheet" />
 <head> <title>Title | Awards </title></head>
<body>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>
<h2>AwardDetails for the @ViewBag.TitleName </h2>
<table>
    <tr>
        <th>
            @Html.DisplayName("Title")
        </th>        
        <th>
            @Html.DisplayNameFor(model => model.AwardYear) &nbsp;
        </th>
        <th>
            @Html.DisplayName("Award")
        </th>
        <th>
            @Html.DisplayNameFor(model => model.AwardCompany)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.TitleName)
        </td>
        
        <td>
            @Html.DisplayFor(modelItem => item.AwardYear)  
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AwardName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.AwardCompany)
        </td>
        
    </tr>
}    
</table>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>
 </body>
</html>

Media.Web/Views/Titles/Cast.cshtml
@model IEnumerable<Movie.Web.MediaServiceReference.Cast>
<html>
<head>    
    <link href="~/Content/Title.css" rel="stylesheet" />
    <title>Title | Cast </title>
</head>
<body>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
    <h2>Cast Details for the @ViewBag.TitleName </h2>
    <div class="DivCast">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Role)
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Role)
                    </td>
                </tr>
            }

        </table>
    </div>
    <p>
        @Html.ActionLink("Back to List", "Index")
    </p>
</body>
</html>

Media.Web/Views/Titles/Details.cshtml
@model Movie.Web.MediaServiceReference.Media
<html>
    <head>
        <link href="~/Content/Title.css" rel="stylesheet" />
        <title> Title | Details</title>
    </head>
<body>
    <div class="DetailDiv">

        <table>
            <tr class="to_label"></tr>
            <tr>
                <td>
                    <b>@Html.DisplayNameFor(model => model.TitleName)    :</b>
                    @Html.DisplayFor(model => model.TitleName)<br />
                    <b>@Html.DisplayNameFor(model => model.ReleaseYear)  :</b>
                    @Html.DisplayFor(model => model.ReleaseYear)
                </td>
            </tr>
        </table>
    </div>

    <p class="DetailDiv"> <b>Genre : </b> @ViewBag.GenreName</p>
    <div>
        <p>
            @Html.ActionLink("AwardDetails", "AwardDetails", new { TitleId = Model.TitleId }) |
            @Html.ActionLink("Cast", "Cast", new { TitleId = Model.TitleId }) |
            @Html.ActionLink("StoryLines", "StoryLines", new { TitleId = Model.TitleId }) |
        </p>
    </div>

    <p>@Html.ActionLink("Back to List", "Index")</p>
</body>
</html>

Media.Web/Views/Titles/Index.cshtml
@model IEnumerable<Movie.Web.MediaServiceReference.Media>
    
<html>
<head>
    <title>Title | Search </title>
    <link href="~/Content/Title.css" rel="stylesheet" />
</head>

<body>
    <h1>Search</h1>
    <div>
        @using (Html.BeginForm("Index", "Titles"))
        {
            <input type="text" id="TitleSearch" name="TitleSearch" value="" placeholder="Search for Movie,Serial and etc,.">
            <input id="Search" type="submit" value="Search" />
        }
    </div>
    <div class="DivScroll">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TitleName)
                </th>
                <th>
                    @Html.DisplayName("Details")
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TitleName)
                    </td>
                    <td>
                        @Html.ActionLink("Details", "Details", new { id = item.TitleId })
                    </td>
                </tr>
            }

        </table>

    </div>


</body>
</html>

Media.Web/Views/Titles/StoryLines.cshtml
@model IEnumerable<Movie.Web.MediaServiceReference.StoryLine>
<html>
<link href="~/Content/Title.css" rel="stylesheet" />
 <head> <title>Title | StoryLine </title></head>
<body>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>
<h2>StoryLines for the @ViewBag.TitleName </h2>
    <div class="DivStoryLine">
        <table>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.TitleName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Type)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Language)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Description)
                </th>
                <th></th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.TitleName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Type)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Language)
                    </td>
                    <td>
                        <p>@Html.DisplayFor(modelItem => item.Description)</p>
                    </td>
                </tr>
            }

        </table>
    </div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>
</body>
</html>